repo: "hero-banner"
canvasCourse: "web-dev-1"

naming: true
restrictFileTypes: true
liveWebsite: true

git:
  numCommits: 2
  allCommitted: true
  allSynced: true

html:
  - path: "index.html"
    valid: true
    bestPractices: true
    has:
      - ['link[href*="Open+Sans"]', 'The Google Font, `Open Sans` (regular, italic & bold) is missing']
      - "div"
      - "div img.img-flex"
      - "div h2"
      - "div p"
    search:
      - "Giant space moths invade Earth"
      - "Our friendly giant, nuclear radiated lizard steps up to battle against the nefarious space moths"
      - "placeholder-16by9\\.svg"

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
    has:
      - ['html', 'box-sizing', 'border-box']
      - ['*', 'box-sizing', 'inherit']
      - ['body', 'margin', 0]
      - ['.img-flex', 'display', 'block']
      - ['.img-flex', 'width', '100%']
      - ['.banner']
    search:
      - "Open Sans"
      - "position: relative"
      - "position: absolute"
      - "left:"
      - "bottom:"
      - "translate"
      - "rgba\\("
      - "max-height"
      - "overflow: hidden"

screenshots:
  - path: "index.html"
    sizes: [650, 1400]
